FROM golang:1.22-alpine AS build
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main ./cmd/s3

FROM alpine:latest
WORKDIR /root/
COPY --from=build /app/main .
COPY .env ./.env
EXPOSE 50053
CMD ["./main"]
