FROM golang:1.22

RUN apt-get update && apt-get install -y \
    bash \
    git \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*
    
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

WORKDIR /auth
COPY . .

RUN go mod tidy
RUN go build -o main ./cmd/auth/main.go

EXPOSE ${AUTH_PORT}

CMD ["./main"]