definitions:
  domain.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      second_name:
        type: string
    type: object
  response.HTTPError:
    properties:
      error:
        type: string
    type: object
  web.GetUserInfoResponse:
    properties:
      user:
        $ref: '#/definitions/domain.User'
    type: object
  web.ProfileResponse:
    properties:
      user:
        $ref: '#/definitions/domain.User'
    type: object
  web.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  web.SignInResponse:
    properties:
      token_string:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
  web.SignUpRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      password:
        type: string
      second_name:
        type: string
    type: object
  web.SignUpResponse:
    properties:
      token_string:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
info:
  contact: {}
paths:
  /{username}:
    get:
      description: The page received basic information about the user
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.ProfileResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: Profile
  /api/user:
    get:
      description: User info
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.GetUserInfoResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: User
  /signin:
    post:
      description: Authorization
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Credentials
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/web.SignInRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.SignInResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: Sign in
  /signup:
    post:
      description: Registration
      parameters:
      - description: Credentials
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/web.SignUpRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.SignUpResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: Sign up
swagger: "2.0"
