definitions:
  auth.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.SignInResponse:
    properties:
      error:
        type: string
      tokenStr:
        type: string
      user:
        $ref: '#/definitions/auth.User'
    type: object
  auth.User:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  domain.User:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  response.HTTPError:
    properties:
      error:
        type: string
    type: object
  users.GetByUsernameResponse:
    properties:
      error:
        type: string
      user:
        $ref: '#/definitions/users.User'
    type: object
  users.User:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  web.UserResponse:
    properties:
      user:
        $ref: '#/definitions/domain.User'
    type: object
info:
  contact: {}
paths:
  /{username}:
    get:
      description: User's page
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.GetByUsernameResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: Page
  /api/user:
    get:
      description: User info
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: User
  /signin:
    post:
      description: Authorization
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Credentials
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/auth.SignInRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.SignInResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: Sign in
  /signup:
    post:
      description: Registration
      parameters:
      - description: Credentials
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/auth.SignInRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.SignInResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/response.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.HTTPError'
      summary: Sign up
swagger: "2.0"
